apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
    containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }} "
        ports:
          - containerPort: 8080
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGODB_URI
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: password
          - name: DATABASE 
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: database 
