name: sonar code analysis 
description: Static Code Analysis
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Perform SonarQube Code Analysis 
      uses: sonarsource/sonarqube-scan-action@master
      with: 
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        
